### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by YYsmith** [subicWang/HOG-SVM-classifer#2]
I use the python3. I meet a issues when load the data. Is there any solution to the mistake?  The details are as follow:
"Traceback (most recent call last):
  File "E:/python/svm/extractFeat.py", line 72, in <module>
    TrainData, TestData = getData(filePath)
  File "E:/python/svm/extractFeat.py", line 32, in getData
    train = np.reshape(data['data'], (10000, 3, 32 * 32))
KeyError: 'data'"

**Comment by maodoudabai** [comment]
> I use the python3. I meet a issues when load the data. Is there any solution to the mistake?  The details are as follow:
> "Traceback (most recent call last):
> File "E:/python/svm/extractFeat.py", line 72, in 
> TrainData, TestData = getData(filePath)
> File "E:/python/svm/extractFeat.py", line 32, in getData
> train = np.reshape(data['data'], (10000, 3, 32 * 32))
> KeyError: 'data'"

盆友，你好！我也遇到了这个问题，请问您知道怎么解决了吗？

**Comment by KalElSuper** [comment]
> > 我用的是python3。我在加载数据时遇到了问题。这个错误有什么办法吗？详细信息如下：
> > “Traceback（最近一次调用最后一次）：
> > 文件”E：/python/svm/extractFeat.py“，第72行，在
> > TrainData中，TestData = getData（filePath）
> > 文件”E：/ python / svm / extractFeat.py“，第32行，在getData 
> > train = np.reshape（data ['data']，（10000,3,32 * 32））
> > KeyError：'data'”
> 
> 盆友，你好！我也遇到了这个问题，请问您知道怎么解决了吗？
您好，您知道怎么解决吗？

**Comment by ZYY1015027303** [comment]
请问KeyError:'data'怎么解决
